name: Release to personal page

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build:prod

    - name: Generate 404
      run: cp docs/index.html docs/404.html

    - name: Publish to personal page
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'docs/1petr0v-github-io-src'
        destination-github-username: '1petr0v'
        destination-repository-name: '1petr0v.github.io'
        user-email: petrov.igor.od+personal_page@gmail.com
        target-branch: main
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF